spring.application.name=LancheriaSpring

spring.datasource.url=jdbc:postgresql://localhost:5434/lancheria
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp
